### ISSUE TITLE
In line 14 of the cohesinKO.main.R: txdb <- TxDb.Mmusculus.UCSC.mm10.ensGene

### ISSUE THREAD

**Issue by dpolychr** [ibn-salem/cohesinKO#2]
The RNAseq data are on mm9. 
But I guess it should be fine to use the mm10 since paralog gene - pairs are not expected to change dramatically between releases?

**Comment by ibn-salem** [comment]
yes, I was thinking to use mm9 but some of the TAD data is in mm10 and also there is unfortunately no TxDb.Mmusculus.UCSC.mm9.ensGene on bioconductor. 
So for the moment, I liftOver TADs and GRBs from mm9 to mm10 to work in mm10.
