### ISSUE TITLE
in the cohesinKO.data.R: maybe filter out genes with low - expression?  

### ISSUE THREAD

**Issue by dpolychr** [ibn-salem/cohesinKO#3]
What would you think, Jonas?

Would it be good to apply this step, and then calculate gene - pairs (using the remaining "meaningful genes")?

Because many rows in the ReadCounts are 0 and therefore in the correlations we get NAs (anyway those are not taken into account later i think)...

Like for example add this line:

ReadCounts.macrophages.filtered = filterGenes(ReadCounts.macrophages, filterTypes = "central", filterCentralType = "median", filterCentralPercentile = 0.3)

They do the same here:

https://htmlpreview.github.io/?https://github.com/andymckenzie/DGCA/blob/master/inst/doc/DGCA.html#filtering-the-input-genes

see section: 

3.2 Filtering the input genes

**Comment by ibn-salem** [comment]
yes, I think this makes sense. 
And yes, in the moment many correlation values are NA and are therefore ignored in the downstream analysis.
