### ISSUE TITLE
Lines 260 - 270: cohesinKO.main.R script

### ISSUE THREAD

**Issue by dpolychr** [ibn-salem/cohesinKO#6]
here the following warning comes up:
Warning message:
In eval(substitute(expr), envir, enclos) : NaNs produced

But maybe this is not important?

**Comment by ibn-salem** [comment]
Thanks Dimitirs, 
this was caused in the log2 calculations where some values where negative. Since we do not use this log2 ratio of fold changes anyway, I removed it.
