### ISSUE TITLE
Lines 422 - 428: cohesinKO.main.R

### ISSUE THREAD

**Issue by dpolychr** [ibn-salem/cohesinKO#8]
Warning messages:
1: attributes are not identical across measure variables; they will be dropped 
2: Too many values at 3998268 locations: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...

**Comment by ibn-salem** [comment]
The first warning is caused in 'gather()' by combining different types into one column as in #7.
The second warning was a problem in separating study and tissue columns for TAD data source as in #7 and is now fixed.
Thanks!
